apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: luis288990/wanderlust-api:latest 
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo-service:27017/wanderlust"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: FRONTEND_URL
          value: "http://frontend-service:3000"
        - name: BACKEND_URL
          value: "http://api-service:8080"
        - name: GOOGLE_CLIENT_ID
          value: "887990"
        - name:  GOOGLE_CLIENT_SECRET
          value: "887990"
          
